repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Fails if there are any ">>>>>" lines in files due to merge conflicts.
      - id: check-merge-conflict
      # Trims trailing whitespace. Allow a single space on the endof .md lines for hard line breaks.
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      # Makes sure files end in a newline and only a newline;
      - id: end-of-file-fixer
      # Attempts to load all TOML files to verify syntax.
      - id: check-toml
      # Attempts to load all yaml files to verify syntax; unsafe: only check syntax, do not load yaml
      - id: check-yaml
        args: ["--unsafe"]
      # Check for symlinks that do not point to anything.
      - id: check-symlinks
      # Fail if staged files are above a certain size.
      # To add a large file, use 'git lfs track <file>'; git add <file> to track large fiels with
      # git-lfs rather than commiting them directly to the git history
      - id: check-added-large-files
        args: ["--maxkb=500"]

        # HALT! Before you exclude a large file and commit it, forever
        # bloating our repo size, did you:
        # (1) use a CLI tool like imageoptim to compress them if they are images
        # (2) think hard about whether using DVC or git-lfs is more appropriate
        #   for the file-such as in the case of CSV files or other data
        exclude: |
          (?x)(
              ^example/large/file.csv|
              ^example/large/sklearn-model.pkl
          )
      # Sort requirements in requirements.txt files.
      - id: requirements-txt-fixer
      # Prevent addition of new git submodules.
      - id: forbid-new-submodules
      # Prevent commiting directly to trunk (since Bitbucket wants us to pay for this feature)
      - id: no-commit-to-branch
        args: ["--branch=trunk"]
      # Detect *your* aws credentials from your ~/.aws/credentials file
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        args: [--config=./pyproject.toml]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args:
          [
            --no-strict-optional,
            --ignore-missing-imports,
            --config-file=./pyproject.toml,
          ]
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args:
          - --config=./pyproject.toml
