name: Build, Test and Publish

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Python 3.8
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.8
      - name: Publish to test pypi
        run: |
          /bin/bash run.sh install 
          /bin/bash run.sh build
          env:
            TEST_PYPI_TOKEN=${{ secrets.TEST_PYPI_TOKEN }}
          /bin/bash run.sh publish:test
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install numpy
      #     pip install pre-commit
      # - name: Analysing the code with pre-commit
      #   run: |
      #     SKIP=no-commit-to-branch pre-commit run --all-files
